### ISSUE TITLE
Does express-mail support Express 4?

### ISSUE THREAD

**Issue by antoniobrandao** [sorich87/express-mail#1]
Hello, does express-mail support Express 4 ?

I'm running into this error when I run the example:

/Users/antoniobrandao/WEBROOT/ABWA/express/app.js:52
app.send('mail', mailOptions, function (error, response) {
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'send'
    at Object.<anonymous> (/Users/antoniobrandao/WEBROOT/ABWA/express/app.js:52:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/antoniobrandao/WEBROOT/ABWA/server.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
[BS] Reloading Browsers...
[gulp] [nodemon] restarting due to changes...
[gulp] [nodemon] starting `node server.js`

/Users/antoniobrandao/WEBROOT/ABWA/express/app.js:25
expressMail.extend(app, {
            ^
TypeError: Object function extend(options) {
  var defaults = {
    generateTextFromHTML: true
  };
  var stub = nodemailer.createTransport('STUB', options.config);
  var transport = nodemailer.createTransport(options.transport, options.config);

  defaults = merge(defaults, options.defaults);

  /**
- Close current transport and replace it with a new one.
  *
- @param {Object} options
- @param {Function} cb
- @api private
  */
  function reload(options, cb) {
    transport.close(function (err) {
      if (err) {
        if (cb) {
          cb(err);
        }
        return;
      }
  
  ```
  defaults = merge({}, options.defaults);
  transport = nodemailer.createTransport(options.transport, options.config);
  
  if (cb) {
    cb();
  }
  ```
  
    });
  }
  
  return function (req, res, next) {
    var app = req.app;
    var ext = app.get('view engine');
    var root = app.get('views');
  
    if (ext[0] !== '.') {
      ext = '.' + ext;
    }
  
    app.mail = {
      reload: reload,
      send: sendFactory(transport, app.render.bind(app), root, ext, defaults),
      stub: sendFactory(stub, app.render.bind(app), root, ext, defaults)
    };
  
    res.mail = {
      reload: reload,
      send: sendFactory(transport, res.render.bind(res), root, ext, defaults),
      stub: sendFactory(stub, res.render.bind(res), root, ext, defaults)
    };
    next();
  };
  } has no method 'extend'
  at Object.<anonymous> (/Users/antoniobrandao/WEBROOT/ABWA/express/app.js:25:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/antoniobrandao/WEBROOT/ABWA/server.js:3:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  [gulp] [nodemon] app crashed - waiting for file changes before starting...
  [BS] Reloading Browsers...

**Comment by sorich87** [comment]
It worked last time I checked, and I know a team using it in production.

**Comment by antoniobrandao** [comment]
I mean if it is compatible with Express version 4 exactly. In the example code there is:

```
var app = express.createServer();
```

That is the Express 3 way of starting an App. For that reason I thought this code could be only v3.\* compatible. 

In Express 4 the same command goes like this:

```
var app = express()
```

So I changed just that line, to start the App the correct Express 4 way. And it gives me the error I showed above. Short version:

```
TypeError: Object function (req, res, next) {
app.handle(req, res, next);
} has no method 'send'
```

It seems like express-mail is failing to extend the save method, or more. I couldn't be sure but it looks like a different version's behaviour. 

If it is indeed compatible with v4, would be nice to see a working example code for it.

**Comment by sorich87** [comment]
@brexis @kamhix please can you help?

@antoniobrandao they're the ones I know using it in production. Hopefully they can help.

**Comment by kamhix** [comment]
@antoniobrandao Hi ! Sorry for the late answer. 

We using express-mail with express 4 and it work. Here is an example.

``` javascript
var express = require('express');
var expressMail = require('express-mail');

var app = express();

var mailConfig = {
  transport: 'SMTP',
  config: {
    service: 'Mandrill',
    auth: {
      user: process.env.MANDRILL_USERNAME,
      pass: process.env.MANDRILL_APIKEY
    }
  },
  defaults: {
    from: 'Express-mail Exemple <no_reply@example.com>'
  }
};

app.use(expressMail(mailConfig));


// Here we send a mail to a email send by a form by POST using a template

app.post('/', function (req, res) {
  var email = req.body.email;

  var mailOptions = {
    to: email,
    subject: 'Express Mail Exemple - A simple test',
    locals: {
      url: 'http://express-mail.herokuapp.com'
    }
  };

  res.mail.send('email.html', mailOptions, function (error) {
    if (error) {
      res.status(400).send('Sorry the mail was not be sent to your email address ' + email + '.\nError: ' + error);
    }
    res.send('A mail has successfully been sent to your email address ' + email);
  });
});

```

**Comment by antoniobrandao** [comment]
Thanks for the example, I will try it out !
